---
- name: Install fzf
  ansible.builtin.apt:
    name:
      - "{{ fzf_package_name }}"
      - bat # Install bat for preview in fzf view
    state: present
  become: true

- name: Find key-bindings.bash
  ansible.builtin.command: find /usr/share/doc -name key-bindings.bash -print -quit
  register: fzf_key_bindings_path
  changed_when: false

- name: Setup fzf key bindings in shell rc files
  ansible.builtin.lineinfile:
    # Ansible by default uses /root as HOME when running with sudo
    path: "{{ item }}"
    line: "source {{ fzf_key_bindings_path.stdout }}"
    state: present
    create: true
  loop: "{{ fzf_shells }}"
  when: fzf_key_bindings_path.stdout != ""

- name: Configure fzf defaults in shell rc files
  ansible.builtin.blockinfile:
    path: "{{ item }}"
    create: true
    block: |
      export FZF_DEFAULT_OPTS="--style full"
      export FZF_CTRL_T_OPTS="
        --walker-skip .git,node_modules,target
        --preview 'batcat -n --color=always {}'
        --bind 'focus:transform-header:file --brief {}'"

      source /usr/share/doc/fzf/examples/completion.bash
  loop: "{{ fzf_shells }}"
